name: "jgnesselbosch's Action in Action"
description: "Greets someone and returns 42"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  answer:
    description: "The answer to everything"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}

